apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: tuya-prometheus-exporter
    app.kubernetes.io/name: tuya-prometheus-exporter
  name: tuya-prometheus-exporter
---
apiVersion: v1
kind: Secret
metadata:
  name: tuya-config
type: Opaque
data:
  config.yaml: ZGV2aWNlczoKICAtIG5hbWU6IHBpLXBsdWcKICAgIGlkOiB4eHh4eHh4eHh4eHh4eHh4eHh4CiAgICBrZXk6ICJ4eHh4eHh4eCIKICAgIGlwOiAxOTIueHgueHgueHgKCmxvZ2dpbmc6CiAgbGV2ZWw6IElORk8KCnNjcmFwZUludGVydmFsOiAxMAo=
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: tuya-prometheus-exporter
    app.kubernetes.io/name: tuya-prometheus-exporter
  name: tuya-prometheus-exporter
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: tuya-prometheus-exporter
    app.kubernetes.io/name: tuya-prometheus-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: tuya-prometheus-exporter
    app.kubernetes.io/name: tuya-prometheus-exporter
  name: tuya-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: tuya-prometheus-exporter
      app.kubernetes.io/name: tuya-prometheus-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: tuya-prometheus-exporter
        app.kubernetes.io/name: tuya-prometheus-exporter
    spec:
      containers:
      - image: ghcr.io/josephabc/tuya-prometheus-exporter:v0.0.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: tuya-prometheus-exporter
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
        - mountPath: /config.yaml
          name: config
          subPath: config.yaml
      serviceAccountName: tuya-prometheus-exporter
      volumes:
      - name: config
        secret:
          secretName: tuya-config
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: tuya-prometheus-exporter
    app.kubernetes.io/name: tuya-prometheus-exporter
  name: tuya-prometheus-exporter
spec:
  endpoints:
  - interval: 10s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: tuya-prometheus-exporter
      app.kubernetes.io/name: tuya-prometheus-exporter
