name: Build and Push Docker Image to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_TAG: ${GITHUB_REF#refs/tags/}
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      # Build and push Docker image for ARM64 (aarch64)
      - name: Build and push ARM64 Docker image
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 -t ghcr.io/${{ github.repository_owner }}/tuya-prometheus-exporter:${{ env.DOCKER_IMAGE_TAG }} .
          docker push ghcr.io/${{ github.repository_owner }}/tuya-prometheus-exporter:${{ env.DOCKER_IMAGE_TAG }}
